name: PHP Laravel Dockerized

services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html # update here (bind mount to src)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # update here (path)
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:9.3.0
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
